version: "3.8"

services:
  agent-monitorujacy:
    build: .
    container_name: projekt4_container
    volumes:
      # LEWA STRONA: Twój dysk | PRAWA STRONA: Wnętrze kontenera
      - ./logs:/app/logs
      - ./shared_data:/app/shared_data
    # Jeśli skrypt się wywali, Docker spróbuje go podnieść
    restart: unless-stopped
