version: "3.8"

services:
  agent-monitorujacy:
    build: .
    container_name: Projekt4
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
      - ./shared_data:/app/shared_data
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_orchestrator
    user: root
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_BLOCK_FS_WRITE_ACCESS=false
      - N8N_BLOCK_FS_READ_ACCESS=false
      - N8N_RUNNERS_ENABLED=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
    volumes:
      - ./shared_data:/root/.n8n-files
      - n8n_data:/root/.n8n
    restart: unless-stopped
    depends_on:
      - agent-monitorujacy

volumes:
  n8n_data:
